---

- name: Download sentences_detailed.csv from tatoeba.org
  get_url: url=https://downloads.tatoeba.org/exports/sentences_detailed.tar.bz2 dest=/tmp/
- name: Decompress sentences_detailed.csv
  unarchive: src=/tmp/sentences_detailed.tar.bz2 dest=/tmp/ remote_src=yes
- name: Run the ngrams.db generation script
  command: tatodetect-generate-ngrams.py /tmp/sentences_detailed.csv {{ngrams_db_file}}
- name: Remove sentences files
  file:
    path: /tmp/{{ item }}
    state: absent
  with_items:
  - sentences_detailed.csv
  - sentences_detailed.tar.bz2
