---

- name: Stop tatodetect daemon if started
  command: service tatodetect stop
  when: install_state is success and force_install == true
  ignore_errors: yes
- name: Install dependencies for cppcms
  apt:
    name: ['make', 'cmake', 'g++', 'libpcre3-dev', 'zlib1g-dev', 'libicu-dev']
    state: present
- name: Fetch cppcms source
  get_url: url=http://downloads.sourceforge.net/project/cppcms/cppcms/1.0.5/cppcms-1.0.5.tar.bz2 dest=/tmp/
- name: Extract source from the archive
  command: tar -jxvf cppcms-1.0.5.tar.bz2 chdir=/tmp/
  when: install_state is failed or force_install == true
- name: Disable testing
  replace:
    path: '/tmp/cppcms-1.0.5/CMakeLists.txt'
    regexp: "^(enable_testing\\(\\))$"
    replace: "#\\1"
- name: Generate makefile
  command: cmake . chdir=/tmp/cppcms-1.0.5
- name: Compile
  command: make -j2 chdir=/tmp/cppcms-1.0.5
- name: Install
  command: make install chdir=/tmp/cppcms-1.0.5
- name: Install dependencies for tatodetect
  apt:
    name: ['libsqlite3-dev', 'libcppdb-dev', 'libcppdb-sqlite3-0']
    state: present
- name: Fetch tatodetect source
  git: repo=https://github.com/Tatoeba/Tatodetect.git dest=/tmp/tatodetect
- name: Generate makefile
  command: cmake . chdir=/tmp/tatodetect
- name: Compile
  command: make -j2 chdir=/tmp/tatodetect
- name: Copy the binary to system-wide location
  command: cp tatodetect /usr/local/bin/tatodetect chdir=/tmp/tatodetect
- name: Copy the ngrams generation tool to system-wide location
  copy:
    remote_src: yes
    src: /tmp/tatodetect/tools/generate.py
    dest: /usr/local/bin/tatodetect-generate-ngrams.py
    mode: 0755
- name: Copy service file to system-wide location
  copy: src=tatodetect.service dest=/etc/systemd/system/tatodetect.service mode=0644
  register: service_file
- name: Copy config file to system-wide location
  template: src=tatodetect.js.j2 dest=/etc/tatodetect.js mode=0644
- name: Copy default options file to system-wide location
  copy: src=default dest=/etc/default/tatodetect mode=0644

- name: Create user tatodetect
  user:
    name: tatodetect
    system: yes

- name: Download ngrams.db file
  get_url: url={{ngrams_db_download_url}} dest={{ngrams_db_file}} mode=0644
  when: ngrams_create_mode == "download"

- include: generate_ngrams_db.yml
  when: ngrams_create_mode == "generate"

- name: Reload daemons
  systemd:
    daemon_reload: yes
  when: service_file is changed
- name: Start and enable the daemon
  systemd:
    name: tatodetect
    state: started
    enabled: yes
- name: Remove temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /tmp/tatodetect
  - /tmp/cppcms-1.0.5
  - /tmp/cppcms-1.0.5.tar.bz2
